import { describe, expect, it } from "vitest";
import { createGenerationApiHandler } from "../src/services/generationApi";
import { requestThreeGameGeneration } from "../src/services/generationClient";
import {
  buildConfirmedThreeAssets,
  createThreeAssetCandidates,
  generateThreeGameMvp,
  normalizeThreeSceneDirector
} from "../src/services/threeGameService";
import type { AssetRequirement, ThreeGameBrief, ThreeSceneDirector } from "../src/core/types";

function memoryStore() {
  const writes = new Map<string, string>();
  const binaryWrites = new Map<string, Uint8Array>();
  return {
    writeText: async (path: string, content: string) => {
      writes.set(path, content);
    },
    readText: async (path: string) => writes.get(path) ?? null,
    writeBytes: async (path: string, content: Uint8Array) => {
      binaryWrites.set(path, content);
    },
    readBytes: async (path: string) => binaryWrites.get(path) ?? null,
    ensureDir: async () => undefined,
    writes,
    binaryWrites
  };
}

const brief: ThreeGameBrief = {
  genre: "flight_shooter",
  title: "太空猫星尘航线",
  mobileFormat: "portrait_9_16",
  playerFantasy: "玩家驾驶太空猫飞船穿过陨石带。",
  cameraIntent: "追尾飞行镜头，前方危险物清晰可读。",
  movementIntent: "拖动或键盘控制飞船移动。",
  spaceLayout: "短走廊式太空航线，逐步加压。",
  interactionFeedback: ["收集发光", "碰撞震屏", "失败重开", "胜利庆祝"],
  assetNeeds: ["玩家模型", "陨石模型", "收集物模型", "天空盒", "音效"],
  coreLoop: ["移动飞船", "躲避陨石", "收集能量", "达到目标", "重开"],
  mobileControlPlan: "单指拖动控制横向移动。",
  skillWorkflow: ["threejs-game-director", "threejs-gameplay-systems", "threejs-game-qa"]
};

function confirmedModel(assetKey: string, fileName: string): AssetRequirement {
  return {
    assetKey,
    type: "model",
    purpose: `${assetKey} runtime model`,
    style: "low-poly sci-fi",
    generationMode: "model",
    copyrightStatus: "generated",
    spec: `${assetKey} model generated by Tripo`,
    status: "generated",
    prompt: `${assetKey} unique prompt`,
    acceptedFileTypes: [".glb", ".gltf"],
    previewUrl: `/projects/three-confirmed/v1/assets/${fileName}.png`,
    source: "generated",
    fileUrl: `/projects/three-confirmed/v1/assets/${fileName}.glb`,
    provider: "tripo",
    model: "tripo-text-to-model",
    generationParams: { taskId: `${assetKey}-task` },
    approvalStatus: "approved"
  };
}

function confirmedCoreModels() {
  return buildConfirmedThreeAssets([
    confirmedModel("three.model.player", "player"),
    confirmedModel("three.model.hazard", "hazard"),
    confirmedModel("three.model.collectible", "collectible")
  ]);
}

describe("threejs 3D generation", () => {
  it("creates a futuristic tower defense director, assets, and release gates", () => {
    const result = generateThreeGameMvp({
      idea: "未来科幻塔防，建造激光塔和导弹塔防守基地",
      projectId: "three-futuristic-td",
      baseUrl: "https://wow.example",
      viewportMode: "web_16_9",
      gameType3d: "futuristic_tower_defense"
    });

    expect(result.threeSceneDirector.genre).toBe("futuristic_tower_defense");
    expect(result.threeSceneDirector.movementMode).toBe("tower_defense");
    expect(result.threeSceneDirector.layoutMode).toBe("defense_path");
    expect(result.threeSceneDirector.spawnPattern).toBe("tower_waves");
    expect(result.threeSceneDirector.towerDefense).toMatchObject({
      economyRules: { startingEnergy: expect.any(Number) },
      baseRules: { baseHealth: expect.any(Number) },
      buildRules: { buildRadius: expect.any(Number) }
    });
    expect(result.threeSceneDirector.towerDefense?.pathNodes.length).toBeGreaterThanOrEqual(5);
    expect(result.threeSceneDirector.towerDefense?.towers.map((tower) => tower.kind)).toEqual(
      expect.arrayContaining(["laser", "missile", "slow"])
    );
    expect(result.threeSceneDirector.towerDefense?.waves.length).toBeGreaterThanOrEqual(4);

    const assetKeys = result.threeAssetPack.assets.map((asset) => asset.assetKey);
    expect(assetKeys).toEqual(expect.arrayContaining(["three.tower.laser", "three.tower.missile", "three.tower.slow"]));
    expect(result.threeAssetPack.assets.find((asset) => asset.assetKey === "three.tower.laser")?.fileUrl).toBe(
      "builtin://three/futuristic_tower_defense/tower/laser"
    );
    expect(result.threeVerificationReport).toMatchObject({
      towerDefenseLoopChecked: true,
      towerPlacementChecked: true,
      waveProgressionChecked: true,
      baseDamageChecked: true,
      projectileHitChecked: true
    });
    expect(result.deliveryReady).toBe(true);
  });

  it("adds mature runtime feedback, audio, collision, and model quality metadata to 3D projects", () => {
    const result = generateThreeGameMvp({
      idea: "3D 飞机躲避陨石收集能量，要有爆炸、音效和碰撞反馈",
      projectId: "three-feedback-quality",
      baseUrl: "https://wow.example",
      viewportMode: "app_9_16",
      gameType3d: "flight_shooter"
    });

    expect(result.threeSceneDirector.abilities).toEqual(expect.arrayContaining(["boost"]));
    expect(result.threeSceneDirector.collisionRules).toMatchObject({
      damage: 1,
      invincibleMs: expect.any(Number),
      nearMiss: true
    });
    expect(result.threeSceneDirector.feedbackRules).toMatchObject({
      collectParticles: true,
      hitParticles: true,
      explosion: true,
      screenShake: true,
      flash: true
    });
    expect(result.threeSceneDirector.audioCues).toEqual(
      expect.arrayContaining(["collect", "hit", "win", "lose", "explosion", "warning"])
    );
    expect(result.threeSceneDirector.spawnTimeline?.length).toBeGreaterThanOrEqual(3);

    const player = result.threeAssetPlan.assets.find((asset) => asset.assetKey === "three.model.player");
    expect(player).toMatchObject({
      qualityTier: "builtin_low_poly",
      preferredSource: "builtin_low_poly",
      polyBudget: expect.any(Number),
      maxFileSizeMb: expect.any(Number),
      runtimeScale: expect.any(Number),
      colliderShape: "capsule"
    });
    expect(result.threeAssetPack.assets[0].fileUrl).toMatch(/^builtin:\/\/three\/flight_shooter\/player\//);

    expect(result.threeVerificationReport).toMatchObject({
      modelBudgetPassed: true,
      audioFeedbackChecked: true,
      collisionFeedbackChecked: true,
      runtimeEffectsChecked: true,
      genreDifferentiationChecked: true
    });
  });

  it("creates genre-specific directors and model plans for different 3D game types", () => {
    const cases = [
      { genre: "flight_shooter" as const, idea: "3D 飞机躲避陨石收集能量", mustInclude: /spaceship|aircraft|asteroid|energy/i },
      { genre: "runner" as const, idea: "3D 跑酷收集金币", mustInclude: /runner|lane|barrier|coin/i },
      {
        genre: "third_person_collect" as const,
        idea: "3D 第三人称角色收集宝物躲避守卫",
        mustInclude: /third-person|guardian|treasure|patrol/i
      },
      { genre: "exploration" as const, idea: "3D 探索神秘展厅寻找水晶", mustInclude: /explorer|landmark|discovery|crystal/i }
    ];

    const results = cases.map(({ genre, idea }) =>
      generateThreeGameMvp({
        idea,
        projectId: `three-${genre}`,
        baseUrl: "https://wow.example",
        viewportMode: "app_9_16",
        gameType3d: genre
      })
    );

    const signatures = results.map((result) => {
      const director = result.threeSceneDirector;
      return [
        director.genre,
        director.camera,
        director.world.width,
        director.world.depth,
        director.player.start.z,
        director.enemies.map((enemy) => `${enemy.type}:${enemy.behavior}`).join(","),
        director.stages?.map((stage) => stage.label).join("/")
      ].join("|");
    });

    expect(new Set(signatures).size).toBe(results.length);
    results.forEach((result, index) => {
      const prompts = result.threeAssetPlan.assets
        .filter((asset) => asset.assetKey.startsWith("three.model."))
        .map((asset) => asset.prompt)
        .join(" ");
      expect(prompts).toMatch(cases[index].mustInclude);
      expect(result.threeAssetPack.assets[0].generationParams.genreProfileId).toBe(cases[index].genre);
    });
    expect(results[1].threeSceneDirector.player.start.z).toBeLessThan(results[0].threeSceneDirector.player.start.z);
    expect(results[2].threeSceneDirector.movementMode).toBe("free_move");
    expect(results[3].threeSceneDirector.camera).toBe("orbit_showcase");
    expect(results[3].threeSceneDirector.abilities).toContain("scan");
    results.forEach((result) => {
      expect(result.threeVerificationReport.checks.find((check) => check.id === "non_tower_genre_contract")?.passed).toBe(true);
    });
  });

  it("creates an independent Three.js MVP project with readable Chinese 3D artifacts", () => {
    const result = generateThreeGameMvp({
      idea: "手机竖屏太空飞船躲避陨石收集能量",
      projectId: "three-project-test",
      baseUrl: "https://wow.example",
      viewportMode: "app_9_16",
      gameType3d: "flight_shooter"
    });

    expect(result.project.engineType).toBe("threejs3d");
    expect(result.project.sourceLabel).toBe("Three.js 3D");
    expect(result.project.threeSceneDirector?.controls).toContain("touch_drag");
    expect(result.project.threeSceneDirector?.stages?.length).toBeGreaterThanOrEqual(3);
    expect(result.project.threeAssetPlan?.requiredApiKeys).toEqual([
      "TRIPO_API_KEY",
      "GEMINI_API_KEY",
      "ELEVENLABS_API_KEY"
    ]);
    expect(result.project.artifacts.map((artifact) => artifact.fileName)).toEqual(
      expect.arrayContaining([
        "three-design-brief.json",
        "three-scene-director.json",
        "three-asset-plan.json",
        "three-asset-pack.json",
        "three-verification-report.json",
        "cover-poster.json",
        "cover-poster.webp"
      ])
    );
    expect(JSON.stringify(result.project)).not.toContain("�");
    expect(result.assetLoadReport.ready).toBe(true);
    expect(result.fallbacksUsed).toContain("three.model.player:builtin-three");
    expect(result.deliveryReady).toBe(true);
  });

  it("defaults 3D generation to lightweight builtin models and poster artifacts without waiting for Tripo", () => {
    const result = generateThreeGameMvp({
      idea: "3D 飞机躲避障碍收集能量",
      projectId: "three-lightweight-default",
      baseUrl: "https://wow.example",
      viewportMode: "app_9_16",
      gameType3d: "flight_shooter"
    });

    const coreModels = result.threeAssetPack.assets.filter((asset) => asset.assetKey.startsWith("three.model."));

    expect(coreModels).toHaveLength(3);
    expect(coreModels.every((asset) => asset.provider === "builtin-three")).toBe(true);
    expect(coreModels.every((asset) => asset.fileUrl.startsWith("builtin://"))).toBe(true);
    expect(coreModels.every((asset) => asset.generationParams.modelBudget === "low-poly")).toBe(true);
    expect(result.project.artifacts.map((artifact) => artifact.fileName)).toEqual(
      expect.arrayContaining(["cover-poster.json", "cover-poster.webp"])
    );
    expect(result.project.coverPosterUrl).toBeTruthy();
  });

  it("normalizes shallow 3D directors into playable directors", () => {
    const shallowDirector = {
      version: "1",
      genre: "flight_shooter",
      title: "太空猫星尘航线",
      camera: "follow_chase",
      controls: ["keyboard"],
      player: { speed: 1, radius: 9, start: { x: 99, y: -5, z: 99 } },
      world: { width: 1, depth: 1, skyColor: "bad", groundColor: "bad" },
      objectives: { collectTarget: 0, avoidDamage: true, timeLimitMs: 100 },
      enemies: [],
      feedback: { collectPulse: true, hitShake: true, proceduralAudio: true }
    } as ThreeSceneDirector;

    const normalized = normalizeThreeSceneDirector(shallowDirector, brief);

    expect(normalized.controls).toContain("touch_drag");
    expect(normalized.enemies.length).toBeGreaterThanOrEqual(2);
    expect(normalized.stages?.length).toBeGreaterThanOrEqual(3);
    expect(normalized.objectives.collectTarget).toBeGreaterThanOrEqual(3);
    expect(normalized.player.speed).toBeGreaterThanOrEqual(3);
  });

  it("uses uploaded GLB materials in the 3D asset pack", () => {
    const result = generateThreeGameMvp({
      idea: "3D 飞船躲避陨石",
      projectId: "three-uploaded-models",
      baseUrl: "https://wow.example",
      gameType3d: "flight_shooter",
      userMaterials: [
        {
          assetKey: "three.model.player",
          slot: "player",
          fileName: "ship.glb",
          fileUrl: "/projects/three-uploaded-models/v1/assets/ship.glb",
          previewUrl: "/projects/three-uploaded-models/v1/assets/ship.png",
          mimeType: "model/gltf-binary"
        }
      ]
    });

    const player = result.threeAssetPack.assets.find((asset) => asset.assetKey === "three.model.player");
    expect(player?.source).toBe("uploaded");
    expect(player?.fileUrl).toContain("ship.glb");
    expect(result.assetLoadReport.assets.find((asset) => asset.assetKey === "three.model.player")?.runtimeStatus).toBe(
      "browser_pending"
    );
    expect(result.deliveryReady).toBe(true);
  });

  it("creates distinct Tripo model candidates from the 3D brief and director", () => {
    const candidates = createThreeAssetCandidates({
      idea: "手机竖屏飞机射击，躲避陨石并收集发光能量",
      brief,
      director: normalizeThreeSceneDirector({} as ThreeSceneDirector, brief),
      assetBatchId: "three-assets-test"
    });

    expect(candidates.assets.map((asset) => asset.assetKey)).toEqual([
      "three.model.player",
      "three.model.hazard",
      "three.model.collectible"
    ]);
    expect(new Set(candidates.assets.map((asset) => asset.prompt)).size).toBe(3);
    expect(candidates.assets.every((asset) => asset.provider === "tripo")).toBe(true);
    expect(candidates.assets.every((asset) => asset.generationParams.assetBatchId === "three-assets-test")).toBe(true);
  });

  it("sanitizes Tripo prompts so UI/game text is not sent as model generation text", () => {
    const candidates = createThreeAssetCandidates({
      idea: "3.模型,玩家: 玩家可控制 3D 主体，请生成一款 3D Three.js 游戏。",
      brief: {
        ...brief,
        title: "3.模型,收集品: 玩家需要收集的 3D 奖励物。请生成一款 3D Three.js 游戏。",
        playerFantasy: "玩家可控制 3D 主体。请生成一款 3D Three.js 游戏。",
        movementIntent: "玩家通过键盘或触屏移动。"
      },
      director: normalizeThreeSceneDirector({} as ThreeSceneDirector, brief),
      assetBatchId: "three-assets-sanitize"
    });

    for (const asset of candidates.assets) {
      expect(asset.prompt).not.toContain("three.model");
      expect(asset.prompt).not.toContain("Three.js");
      expect(asset.prompt).not.toContain("请生成");
      expect(asset.prompt).not.toContain("玩家");
      expect(asset.prompt).toContain("single 3D model");
      expect(asset.prompt.length).toBeLessThan(700);
    }
  });

  it("sends sanitized model-only prompts to Tripo when creating 3D asset candidates", async () => {
    const prompts: string[] = [];
    let taskIndex = 0;
    const handler = createGenerationApiHandler({
      env: {
        DATA_DIR: "data-three-test",
        PUBLIC_BASE_URL: "https://wow.example",
        TRIPO_API_KEY: "test-tripo-key",
        TRIPO_BASE_URL: "https://openapi.tripo3d.com",
        TRIPO_POLL_INTERVAL_MS: "0"
      },
      storeIO: memoryStore(),
      fetcher: async ({ url, init }) => {
        if (url.includes("/v3/generation/text-to-model")) {
          const body = JSON.parse(init.body);
          prompts.push(body.prompt);
          taskIndex += 1;
          return JSON.stringify({ code: 0, data: { task_id: `task-${taskIndex}` } });
        }
        return JSON.stringify({
          code: 0,
          data: {
            status: "success",
            output: {
              model_url: `https://cdn.example.com/model-${taskIndex}.glb`,
              rendered_image_url: `https://cdn.example.com/model-${taskIndex}.png`
            }
          }
        });
      }
    });

    const response = await handler({
      method: "POST",
      path: "/api/three-asset-candidates",
      body: {
        idea: "three.model.player: player controllable 3D subject. Please generate a Three.js game.",
        projectId: "three-api-prompts",
        gameType3d: "flight_shooter"
      }
    });

    expect(response.status).toBe(200);
    expect(prompts).toHaveLength(3);
    expect(new Set(prompts).size).toBe(3);
    for (const prompt of prompts) {
      expect(prompt).toContain("single 3D model");
      expect(prompt).not.toContain("three.model");
      expect(prompt).not.toContain("Three.js");
      expect(prompt).not.toContain("Please generate");
      expect(prompt.length).toBeLessThan(700);
    }
  });

  it("uses confirmed Tripo models in the 3D asset pack", () => {
    const confirmedThreeAssets = confirmedCoreModels();
    const result = generateThreeGameMvp({
      idea: "手机竖屏飞机射击，躲避陨石并收集发光能量",
      projectId: "three-confirmed-models",
      baseUrl: "https://wow.example",
      gameType3d: "flight_shooter",
      confirmedThreeAssets
    });

    for (const key of ["three.model.player", "three.model.hazard", "three.model.collectible"]) {
      const asset = result.threeAssetPack.assets.find((item) => item.assetKey === key);
      expect(asset?.provider).toBe("tripo");
      expect(asset?.source).toBe("generated");
      expect(asset?.fileUrl).toMatch(/\.glb$/);
    }
    expect(result.fallbacksUsed.filter((item) => item.includes("three.model"))).toEqual([]);
  });

  it("marks unsupported real model URLs as not delivery ready", () => {
    const result = generateThreeGameMvp({
      idea: "3D 飞船躲避陨石",
      projectId: "three-bad-model",
      baseUrl: "https://wow.example",
      gameType3d: "flight_shooter",
      userMaterials: [
        {
          assetKey: "three.model.player",
          slot: "player",
          fileName: "ship.txt",
          fileUrl: "https://cdn.example.com/ship.txt",
          previewUrl: "https://cdn.example.com/ship.png",
          mimeType: "text/plain"
        }
      ]
    });

    expect(result.assetLoadReport.ready).toBe(false);
    expect(result.assetLoadReport.errors.join("\n")).toContain("three.model.player");
    expect(result.deliveryReady).toBe(false);
  });

  it("serves /api/generate-three-game and saves the generated project", async () => {
    const store = memoryStore();
    const handler = createGenerationApiHandler({
      env: { DATA_DIR: "data-three-test", PUBLIC_BASE_URL: "https://wow.example" },
      storeIO: store
    });

    const response = await handler({
      method: "POST",
      path: "/api/generate-three-game",
      body: {
        idea: "手机竖屏太空飞船躲避陨石收集能量",
        projectId: "three-project-api",
        baseUrl: "https://wow.example",
        viewportMode: "app_9_16",
        gameType3d: "flight_shooter",
        confirmedThreeAssets: confirmedCoreModels()
      }
    });

    expect(response.status).toBe(200);
    expect(response.body.project.engineType).toBe("threejs3d");
    expect(response.body.project.threeAssetPack.assets[0].provider).toBe("tripo");
    expect(response.body.assetLoadReport.ready).toBe(true);
    expect(response.body.project.playUrl).toBe("/play/three-project-api/v1");
    expect(Array.from(store.writes.keys()).some((path) => path.includes("three-project-api"))).toBe(true);
  });

  it("localizes remote Tripo model URLs before saving a 3D playable", async () => {
    const store = memoryStore();
    const confirmedThreeAssets = buildConfirmedThreeAssets([
      confirmedModel("three.model.player", "player"),
      confirmedModel("three.model.hazard", "hazard"),
      {
        ...confirmedModel("three.model.collectible", "collectible"),
        fileUrl: "https://openapi.cdn.tripo3d.com/task/collectible.glb?auth_key=temporary"
      }
    ]);
    const handler = createGenerationApiHandler({
      env: { DATA_DIR: "data-three-test", PUBLIC_BASE_URL: "https://wow.example" },
      storeIO: store,
      remoteAssetFetcher: async (url) => {
        expect(url).toContain("collectible.glb");
        return {
          contentType: "model/gltf-binary",
          bytes: new Uint8Array([0x67, 0x6c, 0x54, 0x46])
        };
      }
    });

    const response = await handler({
      method: "POST",
      path: "/api/generate-three-game",
      body: {
        idea: "3D collectible localization",
        projectId: "three-localized-models",
        baseUrl: "https://wow.example",
        viewportMode: "app_9_16",
        gameType3d: "flight_shooter",
        confirmedThreeAssets
      }
    });

    const collectible = response.body.project.threeAssetPack.assets.find(
      (asset: AssetRequirement) => asset.assetKey === "three.model.collectible"
    );

    expect(response.status).toBe(200);
    expect(collectible.fileUrl).toBe(
      "/projects/three-localized-models/v1/assets/three-models/three.model.collectible.glb"
    );
    expect(collectible.generationParams.originalRemoteUrl).toContain("openapi.cdn.tripo3d.com");
    expect(collectible.generationParams.localized).toBe(true);
    expect(
      store.binaryWrites.has(
        "data-three-test/projects/three-localized-models/versions/v1/assets/three-models/three.model.collectible.glb"
      )
    ).toBe(true);
  });

  it("generates a lightweight builtin 3D game when no core 3D models are confirmed", async () => {
    const handler = createGenerationApiHandler({
      env: { DATA_DIR: "data-three-test", PUBLIC_BASE_URL: "https://wow.example" },
      storeIO: memoryStore()
    });

    const response = await handler({
      method: "POST",
      path: "/api/generate-three-game",
      body: {
        idea: "手机竖屏飞机射击，躲避陨石并收集发光能量",
        projectId: "three-project-api",
        baseUrl: "https://wow.example",
        viewportMode: "app_9_16",
        gameType3d: "flight_shooter"
      }
    });

    expect(response.status).toBe(200);
    expect(response.body.project.engineType).toBe("threejs3d");
    expect(response.body.deliveryReady).toBe(true);
    expect(response.body.project.threeAssetPack.assets).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ assetKey: "three.model.player", provider: "builtin-three" }),
        expect.objectContaining({ assetKey: "three.model.hazard", provider: "builtin-three" }),
        expect.objectContaining({ assetKey: "three.model.collectible", provider: "builtin-three" })
      ])
    );
  });

  it("accepts futuristic tower defense through the generate-three-game API", async () => {
    const handler = createGenerationApiHandler({
      env: { DATA_DIR: "data-three-td-api-test", PUBLIC_BASE_URL: "https://wow.example" },
      storeIO: memoryStore()
    });

    const response = await handler({
      method: "POST",
      path: "/api/generate-three-game",
      body: {
        idea: "未来科幻塔防，建造激光塔和导弹塔防守基地",
        projectId: "three-td-api",
        gameType3d: "futuristic_tower_defense",
        viewportMode: "web_16_9"
      }
    });

    expect(response.status).toBe(200);
    expect(response.body.project.threeSceneDirector.genre).toBe("futuristic_tower_defense");
    expect(response.body.project.threeSceneDirector.movementMode).toBe("tower_defense");
  });

  it("posts 3D generation requests through the browser client", async () => {
    const result = await requestThreeGameGeneration(
      {
        idea: "3D 跑酷收集金币",
        projectId: "three-client",
        baseUrl: "https://wow.example",
        viewportMode: "app_9_16",
        gameType3d: "runner"
      },
      async (url, init) => {
        expect(url).toBe("/api/generate-three-game");
        expect(JSON.parse(String(init?.body)).idea).toContain("跑酷");
        return new Response(
          JSON.stringify({
            project: { engineType: "threejs3d" },
            deliveryReady: true,
            assetLoadReport: { ready: true, assets: [], errors: [] }
          }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }
    );

    expect(result.project.engineType).toBe("threejs3d");
    expect(result.deliveryReady).toBe(true);
  });
});
